source_file: audios/finale_without_you.mp3
output_file: outputs/finale_without_you_remixed.mp3
# Overlap fade-out of one segment with fade-in of the next (milliseconds).
fade_overlap_ms: 200
session_configs:
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
- start: 0
  end: 259
  fade_in: 100
  fade_out: 1000
